name: smiley
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  calendar_date_picker2: ^1.0.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.1
  provider: ^6.0.3
  cloud_firestore: ^4.17.4
  path_provider: ^2.0.2
  shared_preferences: ^2.2.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/diary_on.png
    - assets/images/diary_off.png
    - assets/images/setting_on.png
    - assets/images/setting_off.png
    - assets/images/social_on.png
    - assets/images/social_off.png
    - assets/images/analyze_on.png
    - assets/images/analyze_off.png
    - assets/images/chatRobot_on.png
    - assets/images/chatRobot_off.png
    - assets/images/default_avatar.png
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700
